"""initial_tables

Revision ID: f00f11f7c1a2
Revises: 
Create Date: 2026-02-07 16:23:18.819150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f00f11f7c1a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    op.create_table('users',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('stores',
    sa.Column('store_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('engine', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'PROVISIONING'"), nullable=False),
    sa.Column('namespace', sa.Text(), nullable=False),
    sa.Column('helm_release', sa.Text(), nullable=False),
    sa.Column('store_url', sa.Text(), nullable=False),
    sa.Column('error_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('store_id'),
    sa.UniqueConstraint('helm_release'),
    sa.UniqueConstraint('namespace')
    )
    op.create_index('idx_store_status', 'stores', ['status'], unique=False)
    op.create_index('idx_store_user', 'stores', ['user_id'], unique=False)
    op.create_table('provisioning_steps',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('store_id', sa.Text(), nullable=False),
    sa.Column('step', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_events',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('store_id', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_event_store', 'store_events', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_event_store', table_name='store_events')
    op.drop_table('store_events')
    op.drop_table('provisioning_steps')
    op.drop_index('idx_store_user', table_name='stores')
    op.drop_index('idx_store_status', table_name='stores')
    op.drop_table('stores')
    op.drop_table('users')
    # ### end Alembic commands ###
